### ISSUE TITLE
CW1

### ISSUE THREAD

**Issue by oleksandrblazhko** [oleksandrblazhko/ai202-lobko#12]
https://drive.google.com/file/d/1Jupr5VQFJpOmHJSJY9Vu2JgmrSXgxk2I/view

**Comment by Daniil-Lobko** [comment]
- Тож, ми маємо потребу у чистому повітрі оточуючої середи. 

1.  Зрозумілість цієї потреби, як я вважаю, коментувати не потрібно, адже не виникає жодних запитань, що дійсно тут мається на увазі.
2.  Цінність чистого повітря, як ми знаємо, є навіть безцінною, тож цієї проблеми теж не може виникати.
3.  Актуальність у чистому повітрі теж визначається як абсолютна актуальність, тож актуальність не є проблемою в даному випадку.

- Тож, ми маємо 3х прецедентів: 

1. Охоронець забезпечує особисту безпеку, менеджер охоронного агентства забезпечує необхідною актуальною інформацією стосовно надання послуг цій самій особистій безпеці 
2. Сервіс надання місцерозташування чистого повітря надає актуальні місця розташування природних зон
3. Менеджер надання дозволу для участі в спортивних змаганнях регулює процес подання заяви і його розглядання.

**Comment by oleksandrblazhko** [comment]
перше завдання- 0.5 бали
друге завдання - 1.5 бали
оцінка = 2 бали
